export const mockEquipmentData = [
  {
    id: 1,
    equipment_type: "own",
    equipment_category: "Computer",
    equipment_name: "Dell Latitude 5420",
    equipment_descriptions: "Business laptop with 14-inch display, 16GB RAM, 512GB SSD",
    purchase_number: "PO-2025-001",
    ssn_number: "SSN-001-2025",
    purchase_type: "In store",
    date_of_purchase: "2025-01-15",
    purchase_price: "1299.99",
    vendor_supplier: "Dell Technologies",
    vendor_supplier_location: "Office Floor 2",
    vendor_supplier_contact: "+1-555-0123",
    warranty_avaiability: "Yes",
    warranty_period: "3 years",
    memo: "Standard business laptop configuration",
    signature_type: "Digital",
    equipment_image: null,
    purchase_bill: null,
    address_line1: "123 Tech Street",
    address_line_2: "Suite 100",
    city: "San Francisco",
    state: "CA",
    zip_code: "94105",
    changed_by_detail: {
      full_name: "John Smith"
    },
    equipment_deactivated_date: null,
    equipment_status: "available"
  },
  {
    id: 2,
    equipment_type: "own",
    equipment_category: "Printer",
    equipment_name: "HP LaserJet Pro M404dn",
    equipment_descriptions: "Monochrome laser printer with duplex printing",
    purchase_number: "PO-2025-002",
    ssn_number: "SSN-002-2025",
    purchase_type: "In store",
    date_of_purchase: "2025-02-20",
    purchase_price: "399.99",
    vendor_supplier: "HP Inc.",
    vendor_supplier_location: "Print Room",
    vendor_supplier_contact: "+1-555-0124",
    warranty_avaiability: "Yes",
    warranty_period: "1 year",
    memo: "Department printer for high-volume printing",
    signature_type: "Digital",
    equipment_image: null,
    purchase_bill: null,
    address_line1: "123 Tech Street",
    address_line_2: "Suite 100",
    city: "San Francisco",
    state: "CA",
    zip_code: "94105",
    changed_by_detail: {
      full_name: "Sarah Johnson"
    },
    equipment_deactivated_date: null,
    equipment_status: "available"
  },
  {
    id: 3,
    equipment_type: "rent",
    equipment_category: "Network",
    equipment_name: "Cisco Meraki MR46",
    equipment_descriptions: "Wi-Fi 6 access point for enterprise networks",
    purchase_number: "PO-2025-003",
    ssn_number: "SSN-003-2025",
    purchase_type: "Online",
    date_of_purchase: "2025-03-10",
    purchase_price: "899.99",
    vendor_supplier: "Cisco Systems",
    vendor_supplier_location: "Office Floor 1",
    vendor_supplier_contact: "+1-555-0125",
    warranty_avaiability: "Yes",
    warranty_period: "2 years",
    memo: "Enterprise-grade WiFi access point",
    signature_type: "Digital",
    equipment_image: null,
    purchase_bill: null,
    address_line1: "123 Tech Street",
    address_line_2: "Suite 100",
    city: "San Francisco",
    state: "CA",
    zip_code: "94105",
    changed_by_detail: {
      full_name: "Mike Wilson"
    },
    equipment_deactivated_date: "2025-10-20",
    equipment_status: "unavailable"
  },
  {
    id: 4,
    equipment_type: "rent",
    equipment_category: "Display",
    equipment_name: "Samsung Smart TV QN65",
    equipment_descriptions: "65-inch 4K Smart TV for presentations",
    purchase_number: "PO-2025-004",
    ssn_number: "SSN-004-2025",
    purchase_type: "In store",
    date_of_purchase: "2025-04-05",
    purchase_price: "1299.99",
    vendor_supplier: "Samsung Electronics",
    vendor_supplier_location: "Conference Room A",
    vendor_supplier_contact: "+1-555-0126",
    warranty_avaiability: "Yes",
    warranty_period: "2 years",
    memo: "Conference room display for presentations",
    signature_type: "Digital",
    equipment_image: null,
    purchase_bill: null,
    address_line1: "123 Tech Street",
    address_line_2: "Suite 100",
    city: "San Francisco",
    state: "CA",
    zip_code: "94105",
    changed_by_detail: {
      full_name: "Emily Brown"
    },
    equipment_deactivated_date: null,
    equipment_status: "available"
  },
  {
    id: 5,
    equipment_type: "own",
    equipment_category: "Audio/Video",
    equipment_name: "Logitech Rally System",
    equipment_descriptions: "Video conferencing system with premium audio",
    purchase_number: "PO-2025-005",
    ssn_number: "SSN-005-2025",
    purchase_type: "In store",
    date_of_purchase: "2025-05-15",
    purchase_price: "2999.99",
    vendor_supplier: "Logitech",
    vendor_supplier_location: "Meeting Room 3",
    vendor_supplier_contact: "+1-555-0127",
    warranty_avaiability: "No",
    warranty_period: "3 years",
    memo: "Premium video conferencing system",
    signature_type: "Digital",
    equipment_image: null,
    purchase_bill: null,
    address_line1: "123 Tech Street",
    address_line_2: "Suite 100",
    city: "San Francisco",
    state: "CA",
    zip_code: "94105",
    changed_by_detail: {
      full_name: "David Clark"
    },
    equipment_deactivated_date: null,
    equipment_status: "unavailable"
  }
];